name: Deploy (on tag -> GHCR)

on:
  push:
    tags: [ "v*" ]

env:
  PHP_VERSION: "8.4"
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  DOCKER_BUILDKIT: "1"
  COMPOSER_CACHE_DIR: ~/.cache/composer

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: intl, pdo_mysql, zip
          tools: composer:v2
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: composer-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies (no-dev)
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Symfony cache warmup (prod)
        env:
          APP_ENV: prod
          APP_DEBUG: 0
        run: |
          php bin/console cache:clear --env=prod --no-warmup
          php bin/console cache:warmup --env=prod

      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: .
          if-no-files-found: error

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
